### ISSUE TITLE
Request to include selection menus

### ISSUE THREAD

**Issue by pdmayer** [yorikvanhavre/FreeCAD-manual#13]
Hi I have been trying to follow your really excellent tutorial but have been getting into a real pickle over what should be simple things because it it not clear to me what selections should be made. For example adjusting the placement of the door. At what level and where in the object tree is this carried out? Is this done in Root>Door >Sketch > Base >Placement>Axis or Position. Or Root>Door >Base >Placement>Axis or Position Or in the relevant wall ? I'm not sure if there is a better place to raise this issue.

**Comment by yorikvanhavre** [comment]
Hi,
There are many ways to set the correct placement of a door, the best way is simply to move it with the move tool. Note that this manual is very obsolete as it was written for 0.16, the latest versions of FreeCAD have improved a lot so the manual is no longer very accurate. The best place to ask questions is the forum at https://forum.freecadweb.org , there is a dedicated "Arch & BIM" section

**Comment by pdmayer** [comment]
Hi,

 

Many thanks for your reply, I’ll go to the forum.

 

Kind regards

 

Peter
