### ISSUE TITLE
downloadable pdf version directly from the repository

### ISSUE THREAD

**Issue by noor-tg** [yorikvanhavre/FreeCAD-manual#14]
where I would find the pdf version of the manual ?
it will be easer to set it as a release in this repository .

thank you

**Comment by yorikvanhavre** [comment]
It's all here at the moment: https://freecadweb.org/manual/
I'll upload them to the releases, though

**Comment by noor-tg** [comment]
thank you @yorikvanhavre . but the released manual is for 0.16 not for the latest 0.19 . is there manual for 0.19 ?

**Comment by yorikvanhavre** [comment]
Not yet unfortunately
